INSERT INTO user (username, fullname,password, photoid) values ('User1@fakeemail.com', 'GreggyP', 'User1',2);
INSERT INTO user (username, fullname,password, photoid) values ('User2@fakeemail.com', 'BobbyK', 'User2',3);
INSERT INTO user (username, fullname,password, photoid) values ('User3@fakeemail.com', 'HerbS', 'User3',4);
INSERT INTO user (username, fullname,password, photoid) values ('User4@fakeemail.com', 'JohnnyM', 'User4',5);
INSERT INTO user (username, fullname,password, photoid) values ('User5@fakeemail.com', 'MarcC', 'User5',6);
INSERT INTO user (username, fullname,password, photoid) values ('joe@mail.com', 'Joe Sixpack', 'password',1);
Insert into post (userid, post, photoid) values (1,'I am the man!', 6);
Insert into post (userid, post, photoid) values (2,'Reboot it!!', 7);
Insert into post (userid, post, photoid) values (3,'User 3 First Post', 8);
Insert into post (userid, post, photoid) values (4,'User 4 First Post', 9);
Insert into post (userid, post, photoid) values (1,'User 1 Second Post', 10);
Insert into post (userid, post, photoid) values (1,'User 1 Third Post', 11);
Insert into post (userid, post, photoid) values (5,'User 5 First Post', 12);
Insert Into post (userid, referencepost, post) values (2, 1, 'no Im the man!!');
Insert Into post (userid, referencepost, post) values (4, 2, 'you said it');
Insert Into post (userid, referencepost, post) values (1, 3, 'Comment on post id 3');
Insert Into post (userid, referencepost, post) values (1, 4, 'Comment on post id 4');
Insert Into post (userid, referencepost, post) values (1, 1, 'Comment on post id 1 Again');
Insert Into post (userid, referencepost, post) values (2, 1, 'Comment on post id 1 Yet Again');
Insert into following (followerid, followeeid) values (1, 1);
Insert into following (followerid, followeeid) values (1, 2);
Insert into following (followerid, followeeid) values (2, 2);
Insert into following (followerid, followeeid) values (2, 1);
Insert into following (followerid, followeeid) values (4, 1);
Insert into following (followerid, followeeid) values (2, 3);
Insert into following (followerid, followeeid) values (2, 4);
Insert into following (followerid, followeeid) values (1, 5);
Insert into following (followerid, followeeid) values (5, 1);
Insert Into likes (likerid, likeeid, postid) values (2,1,1);
Insert Into likes (likerid, likeeid, postid) values (1,2,2);
Insert Into photo (photoname, mimetype) values ('conn.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('User1.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('User2.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('User3.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('User4.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('User5.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('theman.jpg','Image/Jpeg');
Insert Into photo (photoname, mimetype) values ('reboot.jpg','Image/Jpeg');
Insert Into messages (messengerid, messageeid, subject, message) values ('1','2','first subject', 'first message text');
Insert Into education (userid, school, datestart, datefinished, degree) values (1,'University of Viriginia','10/1/2009', '6/1/2013','BS in Information System');
Insert Into education (userid, school, datestart, datefinished, degree) values (1,'University of Maryland','9/1/2013', '6/1/2015','MS in Computer Science');
Insert Into education (userid, school, datestart, datefinished, degree) values (2,'University of Phoenix','10/1/2011', '6/1/2015','BS');
Insert Into education (userid, school, datestart, datefinished, degree) values (3,'University of California Santa Cruz','10/1/2011', '6/1/2015','BS');
Insert Into education (userid, school, datestart, datefinished, degree) values (4,'University of Georgia','10/1/2011', '6/1/2015','BS');
Insert Into jobs (userid, joblocation, jobtitle, datestart, datefinished) values (1,'Little Ceasers', 'cook', '10/1/2004', '6/1/2006');
Insert Into jobs (userid, joblocation, jobtitle, datestart, datefinished) values (1,'Dominos','driver', '10/1/2006', '6/1/2009');
Insert Into jobs (userid, joblocation, jobtitle, datestart, datefinished) values (2,'Walmart', 'stocker', '10/1/2004', '6/1/2006');
Insert Into jobs (userid, joblocation, jobtitle, datestart, datefinished) values (3,'Best Buy','geek squad', '10/1/2004', '6/1/2006');
Insert Into jobs (userid, joblocation, jobtitle, datestart, datefinished) values (4,'Target', 'cashier', '10/1/2004', '6/1/2006');
Insert Into skills (userid, skill, skilldesc) values (1,'J2EE', 'J2EE Skills');
Insert Into skills (userid, skill, skilldesc) values (1,'.Net','.Net Programming');
Insert Into skills (userid, skill, skilldesc) values (1,'C++', 'MFC Programming');
Insert Into skills (userid, skill, skilldesc) values (1,'Perl','Perl Programming');
Insert Into skills (userid, skill, skilldesc) values (1,'HTML', 'Web Programming');
insert into user (username, fullname, password, photoid) values ('corporate@hooli.com', "Hooli Inc.", "password", 1);
insert into user (username, fullname, password, photoid) values ('corporate@google.com', "Google Inc.", "password", 1);
insert into user (username, fullname, password, photoid) values ('corporate@apple.com', "Apple Computer", "password", 1);
insert into user (username, fullname, password, photoid) values ('corporate@piedpiper.com', "Pied Piper, a Compression Company", "password", 1);
insert into user (username, fullname, password, photoid) values ('billg@microsoft.com', "Microsoft", "password", 1);
insert into user (username, fullname, password, photoid) values ('larry@oracle.com', "Oracle", "password", 1);
insert into user (username, fullname, password, photoid) values ('corporate@mutiny.com', "Mutiny", "password", 1);
insert into user (username, fullname, password, photoid) values ('corporate@hp.com', "Hewlett Packard Inc.", "password", 1);
insert into user (username, fullname, password, photoid) values ('corporate@ibm.com', "Hooli", "password", 1);
insert into user (username, fullname, password, photoid) values ('mikee@dell.com', "Hooli", "password", 1);
insert into messages (messengerid, messageeid, subject,message) values ('3', "1", "Accept Follow Request", "Please accept");
insert into messages (messengerid, messageeid, subject,message) values ('1', "4", "Hello", "I have some news, call me");
insert into messages (messengerid, messageeid, subject,message) values ('5', "1", "Follow him", "Lewis is online now");
insert into messages (messengerid, messageeid, subject,message) values ('2', "4", "Remarks", "Update your jobs");
insert into messages (messengerid, messageeid, subject,message) values ('5', "6", "Touching base", "Hey there!");
insert into messages (messengerid, messageeid, subject,message) values ('6', "1", "Accept Follow Request", "Done");
insert into messages (messengerid, messageeid, subject,message) values ('4', "1", "Accept Follow Request", "Not sure if I know you?");
insert into messages (messengerid, messageeid, subject,message) values ('1', "6", "Unfollow 'cos", "I am quitting");
insert into messages (messengerid, messageeid, subject,message) values ('5', "2", "Its time to call", "Response needed");
